USE finance;

CREATE TABLE DSAI_M_Account_Group_1(Account_Group_Code VARCHAR(3), Account_Group_Name VARCHAR(30),Reporting_Category
VARCHAR(3),Created_User VARCHAR(25),Created_DT DATETIME, Updated_User VARCHAR(25),Updated_DT DATETIME);

CREATE TABLE DSAI_M_GL_Account_2(
GL_Account_Number INT PRIMARY KEY NOT NULL,
Account_Group_Code VARCHAR(3) DEFAULT " " NOT NULL, 
GL_Account_Name VARCHAR(30) DEFAULT " " NOT NULL,
Created_User VARCHAR(15) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(15) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL
);

CREATE TABLE DSAI_M_Country_3(
Country_Code VARCHAR(3) DEFAULT " " NOT NULL,
Country_Name VARCHAR(25) DEFAULT " " NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_M_Company_4(
Country_Code VARCHAR(3) DEFAULT " " NOT NULL,
Company_Code VARCHAR(20) DEFAULT " " NOT NULL,
Company_Name VARCHAR(30) DEFAULT " " NOT NULL,
Subsidiary VARCHAR(1) DEFAULT " " NOT NULL,
Parent_Company VARCHAR(30),
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_M_Local_Currency_5(
Country_Code VARCHAR(5) DEFAULT " " NOT NULL,
Local_Currency_Code VARCHAR(5) DEFAULT " " NOT NULL,
Local_Currency_Name VARCHAR(50) DEFAULT " " NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_M_Reporting_Currency_6(
Reporting_Currency_Code VARCHAR(3) DEFAULT " " NOT NULL,
Reporting_Currency_Name VARCHAR(50) DEFAULT " " NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_M_Exchange_Rate_7(
From_Currency VARCHAR(3) DEFAULT " " NOT NULL,
To_Currency VARCHAR(3) DEFAULT " " NOT NULL,
Historical_Exchange_Rates FLOAT DEFAULT 0.0 NOT NULL,
Month_End_Average_Rate FLOAT DEFAULT 0.0 NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_M_Posting_Period_8(
Period INT DEFAULT 0 NOT NULL,
Month VARCHAR(3) DEFAULT " " NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);
/* not correct */

CREATE TABLE DSAI_M_Fiscal_Year_9(
Fiscal_Year VARCHAR(10) DEFAULT " " NOT NULL,
From_Month VARCHAR(10) DEFAULT " " NOT NULL,
To_Month VARCHAR(10) DEFAULT " " NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_M_Cost_Center_10(
Cost_Center_Code VARCHAR(25) DEFAULT " " NOT NULL,
Cost_Center_Name VARCHAR(30) DEFAULT " " NOT NULL,
Company_Code VARCHAR(3) DEFAULT " " NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);

CREATE TABLE DSAI_T_GL_Posting_11(
GL_Account_Number INT DEFAULT 0 NOT NULL,
Country_Code VARCHAR(3) DEFAULT " " NOT NULL,
Company_Code VARCHAR(20) DEFAULT " " NOT NULL,
Reporting_Currency_Code VARCHAR(3) DEFAULT " " NOT NULL,
Period INT DEFAULT 0 NOT NULL,
Fiscal_Year VARCHAR(3) DEFAULT " " NOT NULL,
Cost_Center_Code VARCHAR(20) DEFAULT " " NOT NULL,
Amount_in_Local_Currency INT DEFAULT 0 NOT NULL,
Created_User VARCHAR(25) DEFAULT " " NOT NULL,
Created_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL,
Updated_User VARCHAR(25) DEFAULT " " NOT NULL,
Updated_DT DATETIME DEFAULT "2019-06-12 10:00:00" NOT NULL);



































































